#region Using

using System.Threading.Tasks;

#endregion

namespace C4rm4x.WebApi.Monitoring.Core
{
    /// <summary>
    /// Interface of a generic monitor service
    /// </summary>
    /// <typeparam name="TMonitor">The type of the result generated by the service</typeparam>
    public interface IMonitorService<TMonitor>
    {
        /// <summary>
        /// The component's identifier which this service is responsible for
        /// </summary>
        object ComponentIdentifier { get; }

        /// <summary>
        /// The component's name with this service is responsible for
        /// </summary>
        string ComponentName { get; }

        /// <summary>
        /// Performs the operation to monitor your service and returns the result of it
        /// </summary>
        /// <returns>The monitor response</returns>
        Task<TMonitor> MonitorAsync();
    }
}
